// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/bug/ent/user"
	"entgo.io/bug/ent/userperms"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPermsCreate is the builder for creating a UserPerms entity.
type UserPermsCreate struct {
	config
	mutation *UserPermsMutation
	hooks    []Hook
}

// SetAdmin sets the "admin" field.
func (upc *UserPermsCreate) SetAdmin(b bool) *UserPermsCreate {
	upc.mutation.SetAdmin(b)
	return upc
}

// SetLicense1 sets the "license_1" field.
func (upc *UserPermsCreate) SetLicense1(b bool) *UserPermsCreate {
	upc.mutation.SetLicense1(b)
	return upc
}

// SetUserID sets the "user_id" field.
func (upc *UserPermsCreate) SetUserID(i int) *UserPermsCreate {
	upc.mutation.SetUserID(i)
	return upc
}

// SetID sets the "id" field.
func (upc *UserPermsCreate) SetID(i int) *UserPermsCreate {
	upc.mutation.SetID(i)
	return upc
}

// SetUser sets the "user" edge to the User entity.
func (upc *UserPermsCreate) SetUser(u *User) *UserPermsCreate {
	return upc.SetUserID(u.ID)
}

// Mutation returns the UserPermsMutation object of the builder.
func (upc *UserPermsCreate) Mutation() *UserPermsMutation {
	return upc.mutation
}

// Save creates the UserPerms in the database.
func (upc *UserPermsCreate) Save(ctx context.Context) (*UserPerms, error) {
	var (
		err  error
		node *UserPerms
	)
	if len(upc.hooks) == 0 {
		if err = upc.check(); err != nil {
			return nil, err
		}
		node, err = upc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserPermsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = upc.check(); err != nil {
				return nil, err
			}
			upc.mutation = mutation
			if node, err = upc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(upc.hooks) - 1; i >= 0; i-- {
			if upc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = upc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, upc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserPerms)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserPermsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (upc *UserPermsCreate) SaveX(ctx context.Context) *UserPerms {
	v, err := upc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upc *UserPermsCreate) Exec(ctx context.Context) error {
	_, err := upc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upc *UserPermsCreate) ExecX(ctx context.Context) {
	if err := upc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upc *UserPermsCreate) check() error {
	if _, ok := upc.mutation.Admin(); !ok {
		return &ValidationError{Name: "admin", err: errors.New(`ent: missing required field "UserPerms.admin"`)}
	}
	if _, ok := upc.mutation.License1(); !ok {
		return &ValidationError{Name: "license_1", err: errors.New(`ent: missing required field "UserPerms.license_1"`)}
	}
	if _, ok := upc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPerms.user_id"`)}
	}
	if _, ok := upc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPerms.user"`)}
	}
	return nil
}

func (upc *UserPermsCreate) sqlSave(ctx context.Context) (*UserPerms, error) {
	_node, _spec := upc.createSpec()
	if err := sqlgraph.CreateNode(ctx, upc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (upc *UserPermsCreate) createSpec() (*UserPerms, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPerms{config: upc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userperms.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userperms.FieldID,
			},
		}
	)
	_spec.Schema = upc.schemaConfig.UserPerms
	if id, ok := upc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := upc.mutation.Admin(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: userperms.FieldAdmin,
		})
		_node.Admin = value
	}
	if value, ok := upc.mutation.License1(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: userperms.FieldLicense1,
		})
		_node.License1 = value
	}
	if nodes := upc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userperms.UserTable,
			Columns: []string{userperms.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		edge.Schema = upc.schemaConfig.UserPerms
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPermsCreateBulk is the builder for creating many UserPerms entities in bulk.
type UserPermsCreateBulk struct {
	config
	builders []*UserPermsCreate
}

// Save creates the UserPerms entities in the database.
func (upcb *UserPermsCreateBulk) Save(ctx context.Context) ([]*UserPerms, error) {
	specs := make([]*sqlgraph.CreateSpec, len(upcb.builders))
	nodes := make([]*UserPerms, len(upcb.builders))
	mutators := make([]Mutator, len(upcb.builders))
	for i := range upcb.builders {
		func(i int, root context.Context) {
			builder := upcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPermsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, upcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, upcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, upcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (upcb *UserPermsCreateBulk) SaveX(ctx context.Context) []*UserPerms {
	v, err := upcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upcb *UserPermsCreateBulk) Exec(ctx context.Context) error {
	_, err := upcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upcb *UserPermsCreateBulk) ExecX(ctx context.Context) {
	if err := upcb.Exec(ctx); err != nil {
		panic(err)
	}
}
