// Code generated by ent, DO NOT EDIT.

package userperms

const (
	// Label holds the string label denoting the userperms type in the database.
	Label = "user_perms"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAdmin holds the string denoting the admin field in the database.
	FieldAdmin = "admin"
	// FieldLicense1 holds the string denoting the license_1 field in the database.
	FieldLicense1 = "license_1"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userperms in the database.
	Table = "user_perms"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_perms"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userperms fields.
var Columns = []string{
	FieldID,
	FieldAdmin,
	FieldLicense1,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
