// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Groups is the predicate function for groups builders.
type Groups func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPerms is the predicate function for userperms builders.
type UserPerms func(*sql.Selector)
